version: '3'

networks:
  note:

services:
  nginx:
    image: nginx:latest
    container_name: nginx-note
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - note

  mysql:
    image: mysql:8.0
    container_name: mysql-note
    restart: always
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: note-db
      MYSQL_USER: admin
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - note

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-note
    restart: always
    volumes:
      - /var/www/html/vendor
      - ./src:/var/www/html
      - ./data/php/php.ini.prod:/usr/local/etc/php/php.ini-production
      - ./data/php/php.ini.dev:/usr/local/etc/php/php.ini-development
    ports:
      - "9000:9000"
    networks:
      - note

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    networks:
      - note
  npm:
    image: node:latest
    container_name: npm-note
    entrypoint: ['npm'] 
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    networks:
      - note
  artisan:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: artisan-note
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['php','/var/www/html/artisan']
    depends_on:
      - mysql
    networks:
      - note
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin-note
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - mysql
    networks:
      - note
