version: '3'


services:
  nginx:
    build: 
      context: .
      dockerfile: nginx.dockerfile
    container_name: nginx-note
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - php
      - mysql
    

  mysql:
    image: mysql:8.0
    container_name: mysql-note
    restart: always
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: note-db
      MYSQL_USER: admin
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-note
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - ./src:/var/www/html