version: '3'

networks:
  laravel:

services:
  nginx:
    image: nginx:latest
    container_name: nginx-note
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/var/www/html
      - ./data/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - php
      - mysql
    networks:
      - laravel
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  mysql:
    image: mysql:8.0
    container_name: mysql-note
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: note-db
      MYSQL_USER: admin
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-note
    volumes:
      - /var/www/html/vendor
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    networks:
      - laravel
  npm:
    image: node:latest
    container_name: npm-note
    entrypoint: ['npm'] 
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    networks:
      - laravel
  artisan:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: artisan-note
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['php','/var/www/html/artisan']
    depends_on:
      - mysql
    networks:
      - laravel
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin-note
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - mysql
    networks:
      - laravel
